[package]
name = "sealvault_dev_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sealvault_core = { path = "../../core" , features = ["without_global_executor"]}

actix-web = "4.2.1"
actix-files = "0.6.2"
env_logger = "0.10.0"
ethers = { git = "https://github.com/agostbiro/ethers-rs", rev = "90abdd5", features = ["legacy", "eip712"] }
dotenv = "0.15.0"
log = { version = "0.4.17", features = ["serde"] }
tokio = "1.24.1"
