[package]
# We prefix with "sealvault_" to avoid collision with the Rust core package
name = "sealvault_core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib"]
name = "uniffi_sealvault_core"

[dependencies]
aead = { version = "0.4.3", features = ["alloc"] }
async-trait = "0.1.56"
base64 = "0.13.0"
chacha20poly1305 = { version = "0.9.1", features = ["std"] }
chrono = "0.4.19"
der = "^0.5.0"
diesel = { version = "2.0.0", features = ["sqlite", "r2d2"] }
diesel_migrations = { version = "2.0.0-rc.0", features = ["sqlite"] }
# `serde` feauture implicitly depends on `pem` in 0.12.1
ecdsa = {version = "0.14", features = ["digest", "sign"]}
# Had to fork to resolve dependency conflict. Pending release of https://github.com/roynalnaruto/svm-rs/pull/67
ethers = { git = "https://github.com/agostbiro/ethers-rs", features = ["legacy", "eip712", "abigen"] }
futures = "0.3.21"
# Git version needed for unreleased https://github.com/paritytech/jsonrpsee/pull/845
jsonrpsee = { git = "https://github.com/paritytech/jsonrpsee", rev="41b8a2c", features = ["server", "http-client", "macros"] }
# Ethers Core has this
k256 = { version = "0.11", features = ["digest", "ecdsa", "keccak256", "pkcs8", "pem"] }
# This is a dependency of Diesel. We add it here to use bundled (statically linked SQLite)
# with the feature flag. We need at least 0.24, bc that bundles SQLite 3.38.0 which
# ships with JSON support compiled in.
libsqlite3-sys = { version = ">=0.24, <0.26.0", features = ["bundled"] }
rand = "0.8.5"
readonly = "0.2.1"
rust-embed = "6.4.0"
sha2 = { version = "^0.9.8" }
serde_json = { version = "1.0.81", features = ["alloc"] }
strum = { version = "0.24.1", features = ["derive", "strum_macros"] }
strum_macros = "^0.24"
thiserror = "1.0.31"
tokio = "1.22.0"
typed-builder = "0.10.0"
uniffi = "0.20.0"
uniffi_macros = "0.20.0"
uuid = { version = "1.1.1", features = ["v4"] }
sha3 = "0.10.1"
hex = "0.4.3"
serde = { version = "1.0.137", features = ["serde_derive", "derive", "alloc"] }
core-foundation-sys = "0.8.3"
core-foundation = "0.9.3"
zeroize = { version = "1.5.6", features = ["derive"] }
olpc-cjson = "0.1.1"
url = { version = "2.2.2", features = ["serde"] }
lazy_static = "1.4.0"
publicsuffix = "2.1.1"
cacache = "10.0.1"
reqwest = { version = "0.11.11" }
reqwest-middleware = "0.1.6"
http-cache-reqwest = "0.5.0"
blake3 = "1.3.1"
generic-array = "0.14.5"
subtle = "2.4.1"
num-traits = "0.2.15"
num-derive = "0.3.3"
env_logger = "0.9.0"
log = { version = "0.4.17", features = ["serde"] }
regex = "1.6.0"
anyhow = "1.0.57"
http = "0.2.8"
itertools = "0.10.3"
email_address = "0.2.3"
rust_decimal = { version = "1.26.1", features = ["maths"] }
data-encoding = "2.3.2"
tempfile = "3.3.0"
dyn-clone = "1.0.9"
argon2 = { version = "0.4.1", features = ["std", "zeroize"] }
zip = "0.6.3"
derive_more = "0.99.17"

[build-dependencies]
# Important to match uniffi dep version in `embedded-uniff-bindgen`
uniffi_build = { version = "0.20.0", features=["builtin-bindgen"] }

[dev-dependencies]
anyhow = { version = "1.0.57", features = ["backtrace"] }
ethers = { git = "https://github.com/agostbiro/ethers-rs", features = ["legacy", "eip712", "abigen-offline", "solc-full"] }

[features]
without_global_executor = []

